name       : kgeography
version    : 23.04.1
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kgeography-23.04.1.tar.xz : c5715b767b303af086d20974154acef61c4c4f3994d54fc24edf5cad957ad681
homepage   : https://kde.org/applications/education/org.kde.kgeography
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : game.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - kiconthemes-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
