name       : kgeography
version    : 18.04.3
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kgeography-18.04.3.tar.xz : 750879395d6eb08384eef350e0d3234f98e386018d2e750bb954db15377c7eee
license    : GPL-2.0
component  : game.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kcoreaddons-devel
    - kitemviews-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
