name       : kgeography
version    : 18.04.1
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/kgeography-18.04.1.tar.xz : 5e0a5c031cdb3430f6a507d8c37174bb9c4ce01369c05b46ee8449245b7c8299
license    : GPL-2.0
component  : game.learning
optimize   : lto
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kcoreaddons-devel
    - kitemviews-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
