name       : kgeography
version    : 17.08.1
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kgeography-17.08.1.tar.xz : 0c721e2272575bd1337ff778301f0e8e30b0fdb99b394efdd3f8828218534ed6
license    : GPL-2.0
component  : game.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kcoreaddons-devel
    - kitemviews-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
