name       : kgeography
version    : 21.08.1
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kgeography-21.08.1.tar.xz : c450d0615d143a112a6882ecb756ef3f601dfeed65e3540703f92248b4a30b73
homepage   : https://kde.org/applications/education/org.kde.kgeography
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : game.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - kiconthemes-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
