name       : kgeography
version    : 21.08.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kgeography-21.08.0.tar.xz : 51cd0692bd32b898e8b2bd452968462480858a2bc1c7984998c856ef1abcc007
homepage   : https://kde.org/applications/education/org.kde.kgeography
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : game.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - kcrash-devel
    - kdoctools-devel
    - kio-devel
    - kiconthemes-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
