name       : kgeography
version    : 17.08.2
release    : 5
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kgeography-17.08.2.tar.xz : 66e23fad7b6fb972511e8c8cc722219a23ae7fba3b028cdc8aecc265c29dcf99
license    : GPL-2.0
component  : game.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kcoreaddons-devel
    - kitemviews-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
