name       : kgeography
version    : 16.12.3
release    : 1
source     :
    - https://download.kde.org/stable/applications/16.12.3/src/kgeography-16.12.3.tar.xz : af5c8d17c4054b614f86b67f9e36eff556cab307156e33f8adf127212d00d3e6
license    : GPL-2.0
component  : game.learning
summary    : KGeography is a geography learning tool
description: |
    KGeography is a geography learning tool
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Gui)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kcoreaddons-devel
    - kitemviews-devel
    - kconfigwidgets-devel
    - kiconthemes-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
